### ISSUE TITLE
Issue with Transient failing to save on some server

### ISSUE THREAD

**Issue by w3guy** [collizo4sky/persist-dismissible-admin-notices#16]
See https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/page/3/#post-10778748

Any idea how to fix this @afragen ??

**Comment by afragen** [comment]
@collizo4sky from what I can tell, this is where PaND is called.

https://github.com/futtta/autoptimize/blob/0a841c72be5b95656d91e2660986aeac58fb6337/classes/autoptimizeMain.php#L541=L561

I don’t know of any inherent value for which `set_site_transient` doesn’t work for the `$expiration`, but the expiration is set for 123 days or 10627200 seconds. The transient key is limited to 191 characters in the database.

Here is where the `admin_notices` is called.

https://github.com/futtta/autoptimize/blob/0a841c72be5b95656d91e2660986aeac58fb6337/classes/autoptimizeMain.php#L181-L190

Seems like the user could add `add_filter( 'autoptimize_filter_extra_activate', ‘__return_false’ );` and the notice would never show. But that doesn’t explain what might be going on.

I’ve found that certain caches memcache, Redis, etc. can clear all the transients at unexpected times. I’ve seen this before. The only way around this is to store the value in the options table instead of as a transient. The problem, as I see it, is then there is no way to remove the value from the options table should the plugin be removed. Transients were made for this.

Without installing and debugging the plugin I can’t tell for sure what the issue may be. Below is the commit that included the admin notice.
https://github.com/futtta/autoptimize/commit/31df9d34ca6897b5ce372fe2e022b010a0504563#diff-1afe934307c9c6d17e6bfd36eb1ce875

I would dig into the conditional. I’m not sure why it needs to have many of those checks.

**Comment by afragen** [comment]
It might be that the following hook is being called before PaND initializes. Setting the priority lower may work. Just throwing out ideas.

https://github.com/futtta/autoptimize/blob/0a841c72be5b95656d91e2660986aeac58fb6337/classes/autoptimizeMain.php#L57

**Comment by afragen** [comment]
It seems that the setup containing the notice loading is called during `plugins_loaded` and PaND is loaded in `admin_init`. This might be the issue. Calling `maybe_run_ao_extra` in `admin_init` might fix it.

I’m not sure what calling PaND in `plugins_loaded` would do, $user is not initialized there.

**Comment by afragen** [comment]
I installed the plugin on my Siteground multisite test server and the notice seems to be staying dismissed. ¯\_(ツ)_/¯ 

This with version 2.4.1

**Comment by w3guy** [comment]
It seems to work excellently well for most users of Autoptimize. Also worked perfectly for me on my test.

This is not a bug in PanD. I'll close this issue. 

I advice the developer over Facebook chat to add a filter to dismiss the notice for any user that might have trouble dismissing the notice.

**Comment by futtta** [comment]
I tend to agree this is probably not a bug in PanD (indeed the issue seems not to happen in all or even most cases and I have never seen it fail myself), but it would be nice to know what the problem is.

If this were an issue with priorities, it would be a problem for all, no?

Some other pointers;
* [webfactory reported](https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/#post-10774326) it did not work on one siteground site but it did on a test-site he created there, so this could be a plugin conflict?
* [he later reported](https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/page/3/#post-10778038) that the transient was not in the db
* [he was also the one](https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/page/3/#post-10778748) to claim that this is a problem with the expire int being too big?

**Comment by futtta** [comment]
@afragen re. all the checks; i only want the notice to show if the user is not optimizing images already, if he has acces to the feature (we're launching gradually) and if the notice has not been dismissed yet.

**Comment by w3guy** [comment]
@futtta Regarding the expire int being big, I wanted him to increase memcache item size so we are sure this is the issue.

**Comment by w3guy** [comment]
So what do your suggest as a solution @futtta?? 

I think adding a filter to disable the notice via code could eventually be the solution going forward incase anyone using the lib come across this issue.

Thought?

**Comment by afragen** [comment]
@futtta I was simply brainstorming ideas for why it might be failing. It actually works as expected for me.

@collizo4sky I don’t think memcache size is the issue. The data stored by the transient is minimal.

**Comment by afragen** [comment]
Doesn’t the filter I referenced above already do this?

**Comment by w3guy** [comment]
I was pretty sure the issue is not memcache size related that was why I wanted him to test with the size increased.

> Doesn’t the filter I referenced above already do this?

I don't know. Maybe @futtta would be able to answer that.

**Comment by futtta** [comment]
that filter would hide the entire "extra" tab, I would (as a last resort)
add a filter to disable the notice.

**Comment by afragen** [comment]
I believe the issue is related to a specific user’s object caching. There can clearly be a lot of variability even among users on the same host.

**Comment by w3guy** [comment]
This issue is officially considered closed.

Adding a filter as an alternative for user having problem dismissing the notice very much look like the only solution.

**Comment by futtta** [comment]
probably yeah, although webfactory's test results with expiry int length
are ... weird.

**Comment by w3guy** [comment]
Weird indeed..

**Comment by futtta** [comment]
I now use `ao-img-opt-plug-123`, if I need a transient with expiration 0 I make that  `ao-img-opt-plug-0`, but how is that different from `ao-img-opt-plug-forever`?

**Comment by afragen** [comment]
0 is automatically converted to 1.

https://github.com/collizo4sky/persist-admin-notices-dismissal/blob/b80673631d14f10af9747283d08434619232c003/persist-admin-notices-dismissal.php#L85

`ao-img-opt-plug-0` == `ao-img-opt-plug-1`

**Comment by futtta** [comment]
one being expiry of 1 second, vs forever becoming 0 so no expiry set?

**Comment by afragen** [comment]
@futtta no, the unit is days. The minimum amount of a dismissal is 1 day.

I seem to recall that numbers between 0 and 1 can work for less than a day, but I could be wrong.
I’m wrong.
